In [1]:
import torch

# Create a tensor with shape 1x2x3
t = torch.arange(1, 1 + 1*2*3, dtype=torch.float32).reshape(1, 2, 3)
print(t.shape)
print(t)


torch.Size([1, 2, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.]]])


In [2]:
t*t

tensor([[[ 1.,  4.,  9.],
         [16., 25., 36.]]])

In [3]:
t1 = torch.tensor([1, 2 ])
t2 = torch.tensor([3, 4])
t1*t2
t1*t2.unsqueeze(1)
t1*t2.unsqueeze(0)
t1*t2.unsqueeze(0).unsqueeze(0)


tensor([[[3, 8]]])